version: '3.8'

services:
  voting-app:
    build: ./voting-app
    image: voting-app:latest
    ports:
      - "5000:80"
    environment:
      - REDIS=redis
    networks:
      - frontend
      - backend
    deploy:
      replicas: 2

  result-app:
    build: ./result-app
    image: result-app:latest
    ports:
      - "5001:80"
    environment:
      - DB=postgres://postgres:password@db/postgres
    networks:
      - frontend
    deploy:
      replicas: 1

  redis:
    image: redis:alpine
    ports:
      - "6379:6379"
    networks:
      - backend

  db:
    image: postgres:13
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
    volumes:
      - db-data:/var/lib/postgresql/data
    networks:
      - backend

  worker:
    build: ./worker
    image: worker:latest
    environment:
      - REDIS=redis
      - DB=postgres://postgres:password@db/postgres
    networks:
      - backend
    deploy:
      replicas: 1

networks:
  frontend:
  backend:

volumes:
  db-data:
