services:
  redis:
    image: redis:alpine
    ports:
      - "6379:6379"

  db:
    image: postgres:15
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: votesdb
    volumes:
      - db-data:/var/lib/postgresql/data
    ports:
      - "5432:5432"

  worker:
    build: ./worker
    ports:
      - "8080:8080"
    environment:
      ASPNETCORE_ENVIRONMENT: Development
      ConnectionStrings__PostgreSqlConnection: "Host=db;Database=votesdb;Username=postgres;Password=password"
      ConnectionStrings__RedisConnection: "redis:6379"
    deploy:
      replicas: 2  # Escala el servicio worker a 2 réplicas
      restart_policy:
        condition: on-failure
    depends_on:
      - db
      - redis

  voting-app:
    build: ./voting-app
    ports:
      - "5000:5000"
    environment:
      FLASK_ENV: development
      REDIS_HOST: redis
      VOTE_API_URL: "http://worker:8080/vote"
    deploy:
      restart_policy:
        condition: on-failure

  result-app:
    build: ./result-app
    ports:
      - "3000:3000"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: votesdb
      POSTGRES_HOST: db
    deploy:
      restart_policy:
        condition: on-failure

volumes:
  db-data:
